[package]
name = "nora"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.46", features = ["derive"] }
nanoid = "0.4.0"
nanoid-dictionary = "0.4.3"
regex = "1.11.2"
tempfile = "3.21.0"
tracing = "0.1.41"
tracing-subscriber = "0.3.20"
